import Head from "next/head";
import Image from "next/image";

import Layout from "@/components/Layout";

import dummyImage from '../../public/images/playstore.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Layout>
         <div className="flex items-center justify-between w-full">
          <div>
            <Image src={dummyImage} alt="Nick Munene" className="w-full h-auto"/>
          </div>
         </div>
        </Layout>
      </main>
    </>
  );
}
