import Head from "next/head";
import Image from "next/image";

import Layout from "@/components/Layout";

import dummyImage from '../../public/images/playstore.png'
import AnimatedText from "@/components/AnimatedText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Layout className="pt-0">
         <div className="flex items-center justify-between w-full">
          <div className="w-1/2">
            <Image src={dummyImage} alt="Nick Munene" className="w-full h-auto"/>
          </div>
          <div className="w-1/2 flex flex-col items-center self-center">
            <AnimatedText className="!text-6xl !text-left" text="Transforming Ideas into Elegant Software Solutions."/>
            
            <p >My expertise lies in crafting robust, scalable, and user-centric software solutions that solve complex challenges. By leveraging my strong analytical skills, attention to detail, and in-depth knowledge of industry best practices, I have helped numerous organizations optimize their operations and achieve their digital goals.</p>
          </div>
         </div>
        </Layout>
      </main>
    </>
  );
}
